### ISSUE TITLE
Speed up install using RSPM or BSPM?

### ISSUE THREAD

**Issue by assignUser** [ropensci-review-tools/pkgcheck-action#28]
Using RSPM binary mirror

**Comment by mpadge** [comment]
While that's notionally a good idea, the whole system is build on BSPM and can't just be subsituted out like that. BSPM is often faster than RSPM anyway, but has the way more important ability to do proper installs of system libraries so they can be linked and shared among packages. RSPM just installs binaries associated with packages in a local file linked only to each package. I could write lots more, but suffice to say ... we'd need to sit together and really work out a strategy if we were to do down this path, because it would involve an entire re-structure of how the `pkgcheck` system is built.

**Comment by assignUser** [comment]
Ah I wasn't aware of that, I'll look into it :)

**Comment by mpadge** [comment]
I think we can close this and address via https://github.com/ropensci-review-tools/pkgcheck/issues/143. That repo holds the dockerfile.
