### ISSUE TITLE
Post results to issue

### ISSUE THREAD

**Issue by assignUser** [ropensci-review-tools/pkgcheck-action#4]
https://github.com/ropensci-review-tools/pkgcheck/issues/94
Post results as issue, easy with gha when run from within the issue. (e.g. via push to branch trigger)

I  don't see the need to have the results posted on every pr like we do with {touchstone} or do you think that is necessary @mpadge ?

**Comment by mpadge** [comment]
Having results posted to a "pkgcheck" issue is actually what I had in mind, and is definitely something i think could be very useful. It seems that you know more about how that might be achieved than me right now. It wouldn't be triggered from within the issue, though, rather on every push whether to default branch or elsewhere, and so the action would need to do a bit of ghql magic to identify the issue, open it if not already, and otherwise insert a new comment. Should all be possible via `actions/github-script`, right? This aspect would nevertheless be relatively low priority until the main issues have been addressed.
