### ISSUE TITLE
Create tests for Dockerfile?

### ISSUE THREAD

**Issue by assignUser** [ropensci-review-tools/pkgcheck-action#5]
Not sure what best practice is in this case as mostly once the image is build successfully it should be fine?
Maybe run `pkgstats::ctags_test()`

**Comment by mpadge** [comment]
My suggestion would be that tests are neither relevant nor important then. If the workflow itself works, then the Dockerfile is obviously okay, so usage of the workflow is the test. I also have no idea what best practice might look like, but suspect it's also not relevant here because it's not a container that will be deployed anywhere in any meaningful sense of the word, so can happily remain untested.
