### ISSUE TITLE
pkgcheck container

### ISSUE THREAD

**Issue by assignUser** [ropensci-review-tools/pkgcheck-action#7]
So at the moment I am using a certain version of my container, which of course uses a set version of your container and thus {pkgcheck} @mpadge 

I am wondering if this makes sense... pre-cran it would make sense to always use latest version of everything but post-cran it would make sense to stick to fixed versions, right? Or should we always use the latest container? Alternatively I can add an input so we can choose?

**Comment by mpadge** [comment]
The rOpenSci workflow for which this has all been developed definitely needs continuously updated containers. The main `pkgcheck` contain is cron'ed to rebuild weekly, with the entire server on which it depends also rebuilding itself weekly. I can't see any real need to use a fixed version, because as said elsewhere, this will all remain very actively maintained software for as long as it is being used as part of the software review process, which means indefinitely.

**Comment by assignUser** [comment]
You are right the usual considerations for reproducibility don't make sense in this use case. 

By the way it is possible to trigger the docker build in this repository from the pkgcheck repository, so we could keep this container up-to-date 1:1 with the base container!

**Comment by assignUser** [comment]
Rolling release it is. And ropensci-review-tools/pkgcheck/pull/121 has the workflow_dispatch trigger.
